# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-anyway:
    #if: github.repository == 'hasadna/anyway'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
           #run: mkdir anyway-report && cd anyway-report 
           repository: mickeyrouash/anyway-reports
          # run: ls -R      
    #- uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "${{ secrets.DOCKER_USERNAME }}  ${{ secrets.DOCKER_PASSWORD }} " && ls -lR
    - name: Build and push anyway Docker image
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mickeyrouash/anyway-report
        tag_with_ref: true
        tag_with_sha: true
        cache_from: ${{ env.DOCKER_REPOSITORY_ANYWAY }}:test
        
        
  

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo "${{ secrets.DOCKER_USERNAME }}  ${{ secrets.DOCKER_PASSWORD }} " && ls -lR

    # Runs a set of commands using the runners shell
    
    
